######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
#logo_on_white: "/img/logo-b.svg"
#logo_on_black: "/img/logo-w.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/TheNeetpiqLab"
  instagram: "https://www.instagram.com/the_neetpiq_lab/"
  youtube: "https://www.youtube.com/@TheNeetpiqLab"
  bluesky: "https://bsky.app/profile/edoardoinamo.bsky.social"
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: true
